### ISSUE TITLE
Pas de certificat HTTPS

### ISSUE THREAD

**Issue by busybox11** [pilattebe/classement-officiel-et-scientifique-des-villes-de-france#2]
La page est bloquée dans certains cas sur certains navigateurs (dans mon cas Firefox sur Android) car il n'y a pas de certificat HTTPS.

**Comment by pilattebe** [comment]
Tu peux me mettre l'url

**Comment by busybox11** [comment]
http://classement-officiel-et-scientifique.pilatte.be/

**Comment by busybox11** [comment]
Ça marche en mettant manuellement le S mais il n'y a pas de redirection, et il semble que Firefox ne le prend pas en compte

**Comment by pilattebe** [comment]
C'est le bon URL, il y a eu des changements aujourd'hui donc c'est pour ça que je demandais. J'ai réglé les problèmes de certificats à l'instant, tu peux réessayer ?

**Comment by pilattebe** [comment]
Et il redirige normalement aussi

**Comment by pilattebe** [comment]
Je considère que c'est résolu

**Comment by busybox11** [comment]
Yes, ça redirige bien :)
